## Mobile Phone Adverts Scraping from an E-Commerce Website

### Import Libraries

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

### Extract Relevant Content from the Website

In [33]:
url= 'https://jiji.ng/mobile-phones'
response= requests.get(url)

# Number of pages to extract
no_of_pages= 200

phone_data=[]
for page in range (1,no_of_pages+1):
    url= f'(url)?page=(page)'
    if response.status_code == 200:
        sp= BeautifulSoup(response.content, 'html.parser')
        #print(sp)

        phones_data= sp.find_all('div', class_ = 'b-list-advert-base__data')


        for phone in phones_data:
            #Extract mobile names
            Name= phone.find('div', class_ = 'b-list-advert-base__data__title')
            phone_name= Name.text.strip() if Name else 'N/A'

            #Extract Type names
            Type= phone.find('div', class_ = 'b-list-advert-base__attrs')
            phone_type= Type.text.strip() if Type else 'N/A'

            #Extract Description
            Desc= phone.find('div', class_ = 'b-list-advert-base__description')
            phone_desc= Desc.text.strip() if Desc else 'N/A'

            #Extract price 
            Price= phone.find('div', class_ = 'b-list-advert-base__data__price')
            phone_price= Price.text.strip() if Price else 'N/A'

            #Append to a list
            phone_data.append(
                {'Mobile': phone_name,
                 'Type': phone_type,
                 'Description': phone_desc,
                 'Price': phone_price        
            })
    else: None
else:
    print('',response.status_code)

    
#Converting into a DataFrame
df= pd.DataFrame(phone_data)
df

 200

,Mobile,Type,Description,Price
0,Apple iPhone 12 64 GB Blue,Refurbished,12 64gb UK working 100% camera good battery he...,"₦ 420,000"
1,New Apple iPhone 15 Pro 128 GB Black,Brand New,"Brand new iPhone 15pro 128gb black, different ...","₦ 1,440,000"
2,Samsung Galaxy S21 FE 5G 256 GB White,Used,Samsung S21 FE 5G \n256gb || 8gb RAM \nDual si...,"₦ 318,900"
3,Apple iPhone XR 64 GB Black,Used,IPhone XR 64gb uk used available,"₦ 255,000"
4,New Samsung Galaxy Z Fold 5 512 GB Gray,Brand New,Almost new Samsung Galaxy Zfold 5 black 512Gb ...,"₦ 1,665,000"
...,...,...,...,...
3995,New Samsung Galaxy Z Fold 5 256 GB White,Brand New,Brand new Samsung Galaxy Z fold 5 now availabl...,"₦ 1,355,000"
3996,New Apple iPhone 16 Pro 256 GB Silver,Brand New,"Just sent from USA, few weeks ago, sealed... o...","₦ 2,300,000"
3997,New Samsung Galaxy Note 10 Plus 256 GB Black,Brand New,Brand new Samsung Galaxy Note 10plus 256gb 12g...,"₦ 385,000"
3998,Google Pixel 7a 128 GB Gray,Used,This pixel 7a is a direct American used phone.,"₦ 400,000"
3999,Apple iPhone 14 Pro Max 128 GB Purple,Used,"Direct Uk used iphone 14pro max 128gb purple, ...","₦ 1,100,000"

### Save to CSV File

In [38]:
df.to_csv('phone_data.csv',index_label=False)